### ISSUE TITLE
Server didn't start correctly on Windows

### ISSUE THREAD

**Issue by FSteinhanses** [lenneTech/cli-starter#4]
Issue: Windows doesn't know command "cp"
Solution: Change/Add the following lines in package.json

` "copy:templates": "cpx  \"./src/templates/**/*\" ./dist/templates",`
 
` "devDependencies": {
    "cpx": "^1.5.0"
  },`

**Comment by kaihaase** [comment]
Hello @FSteinhanses,

thank you for informing us of this issue. I'm not sure if you're using the latest version of the template. Since version 0.0.2 of 15.09.2019 we use `cpy` to copy the templates. I just tried this again on Windows 10 in the PowerShell and it works there. Please try the latest version 0.0.3 and contact me if it doesn't work.

A little hint: If you use the lenne.Tech CLI you can create a new CLI with two commands:
```shell
$ npm i -g @lenne.tech/cli
$ lt c c <NAME_OF_YOUR_NEW_CLI>
```

**Comment by kaihaase** [comment]
@FSteinhanses I found it, I think you're referring to the nest-server-starter and not the cli-starter. I will correct that there. Thanks again for the hint.
